---
- block: # user, group and permission
  - name: Ensure sudo group already existed
    group:
      name: sudo
      state: present
  
  - name: Ensure {{ airflow_group }} group already existed
    group:
      name: "{{ airflow_group }}"
      state: present
  
  - name: Create {{ airflow_user }} user with {{ airflow_group }} group
    user:
      name: "{{ airflow_user }}"
      group: "{{ airflow_group }}"
      shell: /bin/bash
      password: '!'
      state: present

  - name: Add {{ airflow_user }} into sudo group
    user:
      name: "{{ airflow_user }}"
      group: sudo
      append: yes
      state: present

  - name: Ensure sudo group already existed in sudoer file
    lineinfile:
      path: /etc/sudoers
      state: present
      regexp: "^%sudo"
      line: "%sudo	ALL=(ALL:ALL) NOPASSWD: ALL"
      validate: "visudo -cf %s"


- block: # directories
  - name: Ensure {{ airflow_log_path }} directory is created
    file:
      path: "{{ airflow_log_path }}"
      state: directory
      owner: "{{ airflow_user }}"
      group: "{{ airflow_group }}"

  - name: Ensure {{ airflow_pid_path }} directory is created
    file:
      path: "{{ airflow_pid_path }}"
      state: directory
      owner: "{{ airflow_user }}"
      group: "{{ airflow_group }}"

  - name: Ensure {{ airflow_environment_path }} directory is created
    file:
      path: "{{ airflow_environment_path }}"
      state: directory
