---
- name: Include OS family specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_os_family }}.yml"
    - default.yml
  
- include_tasks: airflow_pre.yml
- include_tasks: airflow_install.yml

- block: # Config
  - include_tasks: airflow_search_config.yml
  - include_tasks: airflow_post.yml
  tags:
    - airflow-config
